# Create a playbook called file.yml under /home/bob/playbooks/ directory and use this playbook to create a file called /opt/file.txt on node01 host. The contents of the file must be 
# This file is created by Ansible! 
---
- hosts: node01
  become: true
  tasks:
    - name: create a file
      copy:
        dest: /opt/file.txt
        content: "This file is created by Ansible!"




